In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([1,2,3])
r=np.append(a,b)
res=r.reshape(3,3)


print(res)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(-1)
print(b)

[1 2 3 4 5 6]


In [1]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=a[-1::-1,-1::-1]
print(np.flip(a))
print(b)

[[6 5 4]
 [3 2 1]]
[[6 5 4]
 [3 2 1]]


In [13]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[6,7,8]])
i=a.min()
print(i)

j=a.max()
print(j)

print(a.shape)
sum=0
for x in np.nditer(a):
    print(x)
    sum=sum+x
print("sum",sum)
c=a+b
d=a-b 
e=a*b
print(c,d,e)   

1
6
(2, 3)
1
2
3
4
5
6
sum 21
[[ 4  6  8]
 [10 12 14]] [[-2 -2 -2]
 [-2 -2 -2]] [[ 3  8 15]
 [24 35 48]]


In [14]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[3,4,5],[7,8,9]]])
for x in np.nditer(a):
   print(x)

1
2
3
4
5
6
3
4
5
7
8
9


In [15]:
arr1=np.array([3,4])
arr2=np.array([1,0])
avg=(arr1+arr2)/2
print("avrage of both array",avg)

avrage of both array [2. 2.]


In [1]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[3,4,5],[7,8,9]]])
print(np.mean(a))
print(np.median(a))
values,counts=np.unique(a,return_counts=True)
mode=values[np.argmax(counts)]
print(mode)


4.75
4.5
3
