In [6]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.reshape(6))
print(a)
print(a.shape)
print(a.dtype) 
print(a.itemsize)
print(a.ndim)



[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)
int64
8
2


In [ ]:
import numpy as np
a=np.linspace(25,125,10)
print(a)

[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [14]:
import numpy as np
a=np.array([1,2,3])
print(a)
b=np.array([[[1,2,3],[2,3,4],[4,5,6],[7,8,9]],[[1,2,3],[2,3,4],[4,5,6],[7,8,9]],[[1,2,3],[2,3,4],[5,7,6],[7,8,9]],[[1,2,2],[2,3,4],[4,5,6],[7,8,9]]])
print(b)
print(b[1,0,2])

[1 2 3]
[[[1 2 3]
  [2 3 4]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [2 3 4]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [2 3 4]
  [5 7 6]
  [7 8 9]]

 [[1 2 2]
  [2 3 4]
  [4 5 6]
  [7 8 9]]]
3


In [16]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print(arr)
print(arr[[0,2],:])
print(arr[:,[1,3]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]


In [22]:
import numpy as np

a = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]],
    [[25, 26, 27], [28, 29, 30], [31, 32, 33], [34, 35, 36]],
    [[37, 38, 39], [40, 41, 42], [43, 44, 45], [46, 47, 48]]
])

print(a)
print()
print(a[1,0:2,0:2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]

[[13 14]
 [16 17]]


In [30]:
import numpy as np

a = np.array([[23,56,78,93],[71,82,13,24]])

a[a % 2 == 0] = -1

print(a)

[[23 -1 -1 93]
 [71 -1 13 -1]]


In [34]:
import numpy as np

a = np.array([[23,56,78,93],[71,82,13,24]])
for x in np.nditer(a,op_flags=['readwrite']):
    
    if(x%2!=0):
        x[...]=-1
print(a)        

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [38]:
import numpy as np

a = np.array([1,0,2,0,3,0,4])

idx = np.where(a == 0)

print(idx)

(array([1, 3, 5]),)


In [39]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10, 20, 30],
              [40, 50, 60]])
print(a+b)
print(a*b)

[[11 22 33]
 [44 55 66]]
[[ 10  40  90]
 [160 250 360]]


In [40]:
import numpy as np
arr1=np.array([15,20,25])
arr2=np.array([10,40,37])
result = np.dot(arr1, arr2)
print(result)


1875
