In [4]:
import numpy as np
a=np.array([[6,-8,73,-110],[np.nan,-8,0,94]])
print(a)
a[1,0]=0
print(a)
b=np.array([[6,-8,73,-110],[np.nan,-8,0,94]])
print(b)
b=np.nan_to_num(b,nan=0)
print(b)
t=b.T
print(t)
print(b.reshape(2,4))


[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]


In [ ]:
import numpy as np
a=np.array([[6,-8,73,-110],[np.nan,-8,0,94]])
print(a)
c=np.nan_to_num(a,nan=0)
b=np.where(c<0,0,a)


[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]


In [8]:
import numpy as np
c=np.array([[[1,2,3,5],[5,6,7,8]],[[1,5,6,0],[4,5,6,8]]])
print(c)
print(c.shape)
d=np.moveaxis(c,2,0)
print(d)
print(d.shape)

[[[1 2 3 5]
  [5 6 7 8]]

 [[1 5 6 0]
  [4 5 6 8]]]
(2, 2, 4)
[[[1 5]
  [1 4]]

 [[2 6]
  [5 5]]

 [[3 7]
  [6 6]]

 [[5 8]
  [0 8]]]
(4, 2, 2)


In [ ]:
import numpy as np

arr = np.array([[1, np.nan, 3],
                [4, 5, np.nan],
                [7, 8, 9]])

# Column-wise mean (NaN को ignore करके)
col_mean = np.nanmean(arr, axis=0)

# NaN की positions
inds = np.where(np.isnan(arr))

# NaN को column mean से replace करना
arr[inds] = np.take(col_mean, inds[1])

print(arr)

In [ ]:
import numpy as np
a=np.array([[6,-8,73,-110],[np.nan,-8,0,94]])
print(a)
c=np.nan_to_num(a,nan=0)
b=np.where(c<0,0,a)
